config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :clubs do
    get 'dashboard' => 'dashboard#show'

    resources :members do
      resources :payments
    end

    resources :groups
    resources :tags
    resources :users

    resources :payments do
      get 'send_receipt'
    end

    resources :payment_reasons

    resources :expenses do
      get 'send_receipt'
    end

    resources :expense_reasons
    resources :events
    resources :presences, only: [:index]
    get 'check_presence' => 'presences#check'
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  mount MissionControl::Jobs::Engine, at: '/jobs'
  mount Yabeda::Prometheus::Exporter => '/metrics'
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  belongs_to :club

  has_many :member_groups, dependent: :destroy
  has_many :members, through: :member_groups, dependent: :nullify
  has_many :presences, dependent: :nullify

  validates :name, presence: true

  def member_present_at_date?(member, date)
    presences.where(member:, date:).present?
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < BaseController
  before_action :current_user_is_admin?

  def index
    @groups = @club.groups.page(params[:page])
  end

  def new
    @group = @club.groups.build
  end

  def edit
    @group = @club.groups.find(params[:id])
  end

  def create
    @group = @club.groups.build(group_params)

    if @group.save
      redirect_to club_groups_url(@club), flash: { notice: I18n.t('groups.created') }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @group = @club.groups.find(params[:id])

    if @group.update(group_params)
      redirect_to club_groups_url(@club), flash: { notice: I18n.t('groups.updated') }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @group = @club.groups.find(params[:id])
    @group.destroy

    redirect_to club_groups_url(@club), flash: { success: I18n.t('groups.destroyed') }
  end

  private

  def group_params
    params.require(:group).permit(:name, :default_amount, :mandatory_medical_certificate)
  end
end

app/views/groups/_form.html.erb
<%= simple_form_for [@club, group] do |f| %>
  <%= f.input :name, wrapper_html: { class: 'col-sm-6' } %>
  <%= f.input :default_amount, as: :integer, wrapper_html: { class: 'col-sm-6' } %>
  <%= f.input :mandatory_medical_certificate, wrapper_html: { class: 'col-sm-6' } %>
  <%= f.button :submit, 'Salva gruppo' %>
<% end %>

app/views/groups/_group.html.erb
<%= render "form", group: @group %>

app/views/groups/edit.erb
<%= render "form", group: @group %>

app/views/groups/edit.html.erb
<%= render "form", group: @group %>

app/views/groups/index.html.erb
<h2><%= I18n.t('groups.header') %></h2>
<div class="row">
  <ul class="nav justify-content-end">
    <li>
      <%= link_to I18n.t('groups.new'), new_club_group_path(@club), class: 'btn btn-primary' %>
    </li>
  </ul>
</div>
<%= paginate @groups %>
<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= I18n.t('activerecord.attributes.group.name') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.group.default_amount') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.group.mandatory_medical_certificate') %></th>
      <th scope="col"><%= I18n.t('actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= number_to_currency(group.default_amount) %></td>
        <td><%= group.mandatory_medical_certificate %></td>
        <td>
          <%= link_to edit_club_group_path(@club, group), class: 'text-decoration-none' do %>
            <%= image_tag "edit.svg", aria: { hidden: true }, size: 24 %>
          <% end %>
          <%= link_to club_group_path(@club, group), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'text-decoration-none' do %>
            <%= image_tag "trash.svg", aria: { hidden: true }, size: 24 %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/new.html.erb
<%= turbo_frame_tag @group do %>
  <%= render "form", group: @group %>
<% end %>