config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :clubs do
    get 'dashboard' => 'dashboard#show'

    resources :members do
      resources :payments
    end

    resources :groups
    resources :tags
    resources :users

    resources :payments do
      get 'send_receipt'
    end

    resources :payment_reasons

    resources :expenses do
      get 'send_receipt'
    end

    resources :expense_reasons
    resources :events
    resources :presences, only: [:index]
    get 'check_presence' => 'presences#check'
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  mount MissionControl::Jobs::Engine, at: '/jobs'
  mount Yabeda::Prometheus::Exporter => '/metrics'
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  belongs_to :club

  has_many :member_tags, dependent: :destroy
  has_many :members, through: :member_tags, dependent: :nullify

  validates :name, presence: true
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < BaseController
  before_action :current_user_is_admin?

  def index
    @tags = @club.tags.page(params[:page])
  end

  def new
    @tag = @club.tags.build
  end

  def edit
    @tag = @club.tags.find(params[:id])
  end

  def create
    @tag = @club.tags.build(tag_params)

    if @tag.save
      redirect_to club_tags_url(@club), flash: { notice: I18n.t('tags.created') }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @tag = @club.tags.find(params[:id])

    if @tag.update(tag_params)
      redirect_to club_tags_url(@club), flash: { notice: I18n.t('tags.updated') }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tag = @club.tags.find(params[:id])
    @tag.destroy

    redirect_to club_tags_url(@club), flash: { success: I18n.t('tags.destroyed') }
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/views/tags/_form.html.erb
<%= simple_form_for [@club, tag] do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, 'Save' %>
<% end %>

app/views/tags/edit.html.erb
<%= render "form", tag: @tag %>

app/views/tags/index.html.erb
<h2><%= I18n.t('tags.header') %></h2>
<div class="row">
  <ul class="nav justify-content-end">
    <li>
      <%= link_to I18n.t('tags.new'), new_club_tag_path(@club), class: 'btn btn-primary' %>
    </li>
  </ul>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col"><%= I18n.t('actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td>
          <%= link_to edit_club_tag_path(@club, tag), class: 'text-decoration-none' do %>
            <%= image_tag "edit.svg", aria: { hidden: true }, size: 24 %>
          <% end %>
          <%= link_to club_tag_path(@club, tag), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'text-decoration-none' do %>
            <%= image_tag "trash.svg", aria: { hidden: true }, size: 24 %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tags/new.html.erb
<%= render "form", tag: @tag %>