config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :clubs do
    get 'dashboard' => 'dashboard#show'

    resources :members do
      resources :payments
    end

    resources :groups
    resources :tags
    resources :users

    resources :payments do
      get 'send_receipt'
    end

    resources :payment_reasons

    resources :expenses do
      get 'send_receipt'
    end

    resources :expense_reasons
    resources :events
    resources :presences, only: [:index]
    get 'check_presence' => 'presences#check'
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  mount MissionControl::Jobs::Engine, at: '/jobs'
  mount Yabeda::Prometheus::Exporter => '/metrics'
end

app/models/payment.rb
# frozen_string_literal: true

class Payment < ApplicationRecord
  belongs_to :member
  belongs_to :payment_reason

  validates :amount, :number, :kind, presence: true
  validates :number, uniqueness: { conditions: -> { of_year(Time.current.year) } }

  enum :kind, %i[cash bank other]

  scope :of_year, ->(year) { where(created_at: "#{year}-01-01".to_date.all_year) }

  def in_eur
    "#{(amount / 100.0).round(2)} €"
  end
end

app/controllers/payments_controller.rb
# frozen_string_literal: true

class PaymentsController < BaseController
  before_action :current_user_is_admin?
  before_action :set_member, if: -> { params[:member_id].present? }

  def index
    @member = params[:member_id] ? @club.members.find(params[:member_id]) : nil
    @payment_reason = params[:payment_reason_id] ? @club.payment_reasons.find(params[:payment_reason_id]) : nil

    @payments = @club.payments
    @payments = @payments.joins(:member).where(member: { id: @member.id }) if @member
    @payments = @payments.joins(:payment_reason).where(payment_reason: { id: @payment_reason.id }) if @payment_reason
    @payments = @payments.page(params[:page])
  end

  def new
    @payment = @member.payments.new(number: @club.payments.maximum(:number))
  end

  def edit
    @payment = @member.payments.find(params[:id])
  end

  def create
    @payment = @member.payments.build(payment_params)

    if @payment.save
      redirect_to club_member_url(@club, @member), flash: { notice: I18n.t('payments.created') }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @payment = @member.payments.find(params[:id])

    if @payment.update(payment_params)
      redirect_to club_member_url(@club, @member), flash: { notice: I18n.t('payments.updated') }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @payment = @club.payments.find(params[:id])
    @payment.destroy

    redirect_to club_payments_url(@club), flash: { success: I18n.t('payments.destroyed') }
  end

  def send_receipt
    @payment = @club.payments.find(params[:payment_id])

    ReceiptMailer.with(payment: @payment).member_receipt_email.deliver_later

    redirect_to club_payments_url(@club), flash: { notice: I18n.t('payments.receipt_sent') }
  end

  private

  def payment_params
    params.require(:payment).permit(:amount, :number, :kind, :note, :payment_reason_id)
  end

  def set_member
    @member = @club.members.find(params[:member_id])
  end
end

app/views/payments/_form.html.erb
<%= simple_form_for [@club, member, payment] do |f| %>
  <%= f.input :amount, as: :integer %>
  <%= f.input :number, as: :integer %>
  <%= f.association :payment_reason, required: true, label_method: :reason, collection: @club.payment_reasons %>
  <%= f.input :kind, 
      prompt: 'Seleziona tipo', 
      collection: Payment.kinds.map { |kind, v| [Payment.human_attribute_name("kind.#{kind}"), kind] }
  %>
  <% if payment.created_at %>
    <%= f.input :created_at, disabled: true, as: :date %>
  <% end %>
  <%= f.input :note %>
  <%= f.button :submit, 'Salva pagamento' %>
<% end %>

app/views/payments/edit.html.erb
<h2><%= "Editing payment of #{@member.first_name} #{@member.last_name}" %></h2>

<%= render "form",  member: @member, payment: @payment %>

app/views/payments/index.html.erb
<h2><%= I18n.t('payments.header') %></h2>
<div class="row">
  <ul class="nav justify-content-end">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= @payment_reason&.reason || I18n.t('payment_reasons.select') %>
      </a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to I18n.t('all'), club_payments_path(@club, member_id: @member&.id), class: 'dropdown-item' %>
        </li>
        <% @club.payment_reasons.each do |payment_reason| %>
          <li>
            <%= link_to payment_reason.reason, club_payments_path(@club, payment_reason_id: payment_reason.id, member_id: @member&.id), class: 'dropdown-item' %>
          </li>
        <% end %>
      </ul>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= @member&.full_name || I18n.t('members.select') %>
      </a>
      <ul class="dropdown-menu">
        <li>
          <input type="text" class="form-control" placeholder="<% I18n.t('search') %>" onkeyup="filterMembers(this)">
          <%= javascript_tag nonce: true do %>
            function filterMembers(input) {
            const query = input.value.toLowerCase()
            console.log(query);
            const members = [...document.querySelectorAll('.member')];
            members.forEach((elem) => elem.classList.remove('d-none'));
            members.filter((m) => !m.innerHTML.toLowerCase().includes(query)).forEach((elem) => elem.classList.add('d-none'));
            }
          <% end %>
        </li>
        <li>
          <%= link_to I18n.t('none'), club_payments_path(@club, payment_reason_id: @payment_reason&.id), class: 'dropdown-item' %>
        </li>
        <% @club.members.each do |member| %>
          <li>
            <%= link_to member.full_name, club_payments_path(@club, payment_reason_id: @payment_reason&.id, member_id: member.id), class: 'member dropdown-item' %>
          </li>
        <% end %>
      </ul>
    </li>
  </ul>
</div>
<%= paginate @payments %>
<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= I18n.t('activerecord.attributes.member.name') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.payment.amount') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.payment.payment_reason') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.payment.created_at') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.payment.note') %></th>
      <th scope="col"><%= I18n.t('actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.member.full_name %></td>
        <td><%= number_to_currency(payment.amount) %></td>
        <td><%= payment.payment_reason.reason %></td>
        <td><%= payment.created_at %></td>
        <td><%= truncate(payment.note, length: 25) %></td>
        <td>
          <%= link_to club_payment_send_receipt_path(@club, payment), data: { turbo_method: :get, turbo_confirm: I18n.t('payments.confirm_send')}, class: 'text-decoration-none' do %>
            <%= image_tag "send.svg", aria: { hidden: true }, size: 24 %>
          <% end %>
          <%= link_to edit_club_payment_path(@club, payment, member_id: payment.member.id), class: 'text-decoration-none' do %>
            <%= image_tag "edit.svg", aria: { hidden: true }, size: 24 %>
          <% end %>
          <%= link_to club_payment_path(@club, payment), data: { turbo_method: :delete, turbo_confirm: I18n.t('payments.confirm_destroy')}, class: 'text-decoration-none' do %>
            <%= image_tag "trash.svg", aria: { hidden: true }, size: 24 %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/payments/new.html.erb
<h2><%= "#{I18n.t('payments.new')}: #{@member.first_name} #{@member.last_name}" %></h2>

<%= render "form",  member: @member, payment: @payment %>