config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :clubs do
    get 'dashboard' => 'dashboard#show'

    resources :members do
      resources :payments
    end

    resources :groups
    resources :tags
    resources :users

    resources :payments do
      get 'send_receipt'
    end

    resources :payment_reasons

    resources :expenses do
      get 'send_receipt'
    end

    resources :expense_reasons
    resources :events
    resources :presences, only: [:index]
    get 'check_presence' => 'presences#check'
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  mount MissionControl::Jobs::Engine, at: '/jobs'
  mount Yabeda::Prometheus::Exporter => '/metrics'
end

app/controllers/expenses_controller.rb
# frozen_string_literal: true

class ExpensesController < BaseController
  before_action :current_user_is_admin?

  def index
    @expense_reason = params[:expense_reason_id] ? @club.expense_reasons.find(params[:expense_reason_id]) : nil

    @expenses = @club.expenses
    @expenses = @expenses.joins(:expense_reason).where(expense_reason: { id: @expense_reason.id }) if @expense_reason
    @expenses = @expenses.page(params[:page])
  end

  def new
    @expense = @club.expenses.new
  end

  def edit
    @expense = @club.expenses.find(params[:id])
  end

  def create
    @expense = @club.expenses.build(expense_params)

    if @expense.save
      redirect_to club_expenses_url(@club), flash: { notice: I18n.t('expenses.created') }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @expense = @club.expenses.find(params[:id])

    if @expense.update(expense_params)
      redirect_to club_expenses_url(@club), flash: { notice: I18n.t('expenses.updated') }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @expense = @club.expenses.find(params[:id])
    @expense.destroy

    redirect_to club_expenses_url(@club), flash: { success: I18n.t('expenses.destroyed') }
  end

  def send_receipt
    @expense = @club.expenses.find(params[:expense_id])

    ReceiptMailer.with(expense: @expense).collaborator_receipt_email.deliver_later

    redirect_to club_expenses_url(@club), flash: { notice: I18n.t('expenses.receipt_sent') }
  end

  private

  def expense_params
    params.require(:expense).permit(:amount, :user_id, :expense_reason_id)
  end
end

app/views/expenses/_form.html.erb
<%= simple_form_for [@club, expense] do |f| %>
  <%= f.association :user, label_method: :full_name, collection: @club.users %>
  <%= f.input :amount, as: :integer %>
  <%= f.association :expense_reason, required: true, label_method: :reason, collection: @club.expense_reasons %>
  <%= f.button :submit, 'Salva spesa' %>
<% end %>

app/views/expenses/edit.html.erb
<%= render "form", expense: @expense %>

app/views/expenses/index.html.erb
<h2><%= I18n.t('expenses.header') %></h2>
<div class="row">
  <ul class="nav justify-content-end">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= @expense_reason&.reason || I18n.t('expense_reasons.select') %>
      </a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to I18n.t('all'), club_expenses_path(@club), class: 'dropdown-item' %>
        </li>
        <% @club.expense_reasons.each do |expense_reason| %>
          <li>
            <%= link_to expense_reason.reason, club_expenses_path(@club, expense_reason_id: expense_reason.id), class: 'dropdown-item' %>
          </li>
        <% end %>
      </ul>
    </li>
    <li>
      <%= link_to I18n.t('expenses.new'), new_club_expense_path(@club), class: 'btn btn-primary' %>
    </li>
  </ul>
</div>
<%= paginate @expenses %>
<table class="table">
  <thead>
    <tr>
      <th scope="col"><%= I18n.t('activerecord.attributes.expense.amount') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.expense.expense_reason') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.expense.created_at') %></th>
      <th scope="col"><%= I18n.t('actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= number_to_currency(expense.amount) %></td>
        <td><%= expense.expense_reason.reason %></td>
        <td><%= expense.created_at %></td>
        <td>
          <% if expense.user.present? %>
            <%= link_to club_expense_send_receipt_path(@club, expense), data: { turbo_method: :get, turbo_confirm: I18n.t('expenses.confirm_send')}, class: 'text-decoration-none' do %>
              <%= image_tag "send.svg", aria: { hidden: true }, size: 24 %>
            <% end %>
          <% end %>
          <%= link_to edit_club_expense_path(@club, expense), class: 'text-decoration-none' do %>
            <%= image_tag "edit.svg", aria: { hidden: true }, size: 24 %>
          <% end %>
          <%= link_to club_expense_path(@club, expense), data: { turbo_method: :delete, turbo_confirm: I18n.t('expenses.confirm_destroy')}, class: 'text-decoration-none' do %>
            <%= image_tag "trash.svg", aria: { hidden: true }, size: 24 %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/expenses/new.html.erb
<%= render "form", expense: @expense %>